name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v2
      with:
        rust-version: nightly
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu-latest
        path: target/release/bitch_bot
